language: node_js

node_js:
  - "lts/*"

sudo: false
dist: trusty

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn test

# before_deploy:
#   - yarn build

# deploy:
#   provider: firebase
#   token:
#     secure: "$FIREBASE_TOKEN"
#   message: "your message"
#   skip_cleanup: true
#   on:
#     branch: master
